### ISSUE TITLE
instmipac error with epoch data

### ISSUE THREAD

**Issue by ele2303** [sccn/PACTools#12]
I have been trying to use the pop_pac function on my epoched dataset. I can get the "glm" version to run, but the "instmipac" returns an error: 

EEG = pop_pac(EEG,'Channels',[5  15],[30  100],...
    [4],[4],'method','instmipac','nboot',[],'alpha',[],...
    'nfreqs1',10,'nfreqs2',20,'freqscale','log','bonfcorr',0);

eeg_pac: Method not supported for data format provided
output argument "crossfcoh" (and maybe others) not assigned during call to "eeg_pac".
Error in pop_pac (line 440)
        [~, ~, freqs1, freqs2, alltfX, alltfY,~, pacstruct, tfXtimes, tfYtimes] = eeg_pac(X, Y, EEG.srate,  options{:});

I don't have a problem when using the sample dataset (Simpac_famp_60_fphs_8.set) included with the toolbox. I have the parallel toolbox and using the neuroscience gateway does not make a difference. 
Am I doing something wrong with the input? Shouldn't the instmipac work also with epoched-data?
I am happy to provide the data if that's easier. Thank you

**Comment by nucleuscub** [comment]
Hi @ele2303 , the method "instmipac" only handles continuous data. For epoched data, you may want to use the Event-Related MIPAC ("ermipac"). Note that the sample data (Simpac_famp_60_fphs_8.set) is a continuous segment, so no epochs.
Hope this helps,
Ramon
