### ISSUE TITLE
dot indexing is not supported for variables of this type. 

### ISSUE THREAD

**Issue by hoyunlee** [sccn/PACTools#18]
Hello. I'm new to Matlab and EEGlab both. now I'm using Matlab R2021b 
I tried to use PACTools with the sample EEG set. But, the error message occurred as soon as I ran PACTools.

Dot indexing is not supported for variables of this type. 

it's impossible to close this issue. I hope to complete this issue because it's better to search for the answers more on the web. Thank you.

**Comment by nucleuscub** [comment]
@hoyunlee, please provide an accurate description of how to replicate this issue.
Thks

**Comment by arnodelorme** [comment]
Closing this report since no response.
