### ISSUE TITLE
Analysis of rest eeg with PACT

### ISSUE THREAD

**Issue by akatav** [sccn/PACTools#2]
I have resting state eeg of healthy controls, eyes closed and would like to analyse the PAC values of this population by age/gender. At present, having used the PACT software tool between different frequency ranges (delta-theta, theta-alpha and so on, all between 1-45hz), i am not finding any unique patterns in the data by age. I am using the BonferroniMI, BonholmMI, mi and moduInd95 and 99 values returned by the software (using whole data pooling and leaving all other parameters as default (surrogation=2000, phase bins=2000,significance threshold=0.01,HFO amplitude percentile=2). 

I'd like to know if the pac values returned in each of the above variables represent CFC for one electrode (same location) between the lower and higher frequency band ? Or is it between 2 different electrodes (cross location) for different frequency (phase and amplitude) bands? 

I think that for our purposes, it is better to find the cross location CFC values. 
1. How can this be done with PACT? 
2. Can PACT analyse raw EEG data after epoching it with overlap ? 

Thank you

PS: I was unable to find this project on github and finally after much struggle found it using the search term: l=MATLAB&p=2&q=phase+amplitude+coupling&type=Repositories
This repo does not show up on searching for 'PACT'.
Hence i emailed Dr.Arnaud Delorme earlier.Sorry about that.But i could not subscribe to the eeglablist either!:(

**Comment by nucleuscub** [comment]
@akatav Thanks for your interest. 
It is possible to perform cross-channel PAC analysys with PACTools. You just need to select the channels in the Comp/Chan Indices edit input in the main GUI.
Regarding your second  question, I do think is valid to perfmorm the analysis in overlapped trials.
Let me knwo any other question.
 Best,
R
