### ISSUE TITLE
s_rate typo

### ISSUE THREAD

**Issue by AlvinRolling** [sccn/PACTools#3]
In `eeg_pac_test_cases.m`, there is a typo in **line 208**. The second **srate** should be **s_rate**.
```
[~, data_pac,t_outtmp]  = pop_genpac(fc,fm,tlimits,'Ac',5,'Am',1,'srate',s_rate,'cpfunc','block','blockamp',1, 'nsegm',nsegm,'plot_flag', plot_flag,'padtime',padtime,'snr',snrval,'m',1,'ntrials',n_trials,'maxshift',10);
```

**Comment by nucleuscub** [comment]
Thks! Fixed in : https://github.com/sccn/PACTools/commit/b82d2fbe8e027d7b94db2bd12d8b37b2749c947a
